"""Type stubs for ``pdsfile.pdscache`` (see the module docstring there).

The implementation is unannotated (modernization ground rule 5); these stubs
declare the public surface frozen in ``tests/api/api_manifest.json``. Types are
derived from the implementation and its docstrings; where the truth is broader
than a single concrete type, the broader type is declared.
"""

# The manifest freezes these four stdlib module names as public attributes of
# this module (callers may reach them as ``pdsfile.pdscache.sys`` etc.), so the
# stubs re-export them.
import builtins
import os as os
import random as random
import sys as sys
import time as time
from collections.abc import Callable, Iterable
from typing import Any

# rms-pdslogger ships no py.typed marker, so a PdsLogger cannot be named here.
_PdsLogger = Any

MEMCACHED_LOADED: bool
MAX_BLOCK_SECONDS: float

class PdsCache: ...

class DictionaryCache(PdsCache):
    # `dict` and `keys` are attribute names here, so the builtin types they
    # shadow are written qualified throughout this class body.
    dict: builtins.dict[Any, tuple[Any, float | None]]
    keys: builtins.set[Any]
    lifetime: float | None
    lifetime_func: Callable[[Any], float] | None
    limit: int
    slop: float
    logger: _PdsLogger | None
    pauses: int
    preload_eligible: bool
    def __init__(
        self,
        lifetime: float | Callable[[Any], float] = 86400,
        limit: int = 1000,
        logger: _PdsLogger | None = None,
    ) -> None: ...
    def flush(self) -> None: ...
    def wait_for_unblock(self, funcname: str = '') -> None: ...
    def wait_and_block(self, funcname: str = '') -> None: ...
    def unblock(self, flush: bool = True) -> None: ...
    def is_blocked(self) -> bool: ...
    def pause(self) -> None: ...
    @property
    def is_paused(self) -> bool: ...
    def resume(self) -> None: ...
    def __contains__(self, key: Any) -> bool: ...
    def __len__(self) -> int: ...
    def get(self, key: Any) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def get_multi(self, keys: Iterable[Any]) -> builtins.dict[Any, Any]: ...
    def get_local(self, key: Any) -> Any: ...
    def get_now(self, key: Any) -> Any: ...
    def set(self, key: Any, value: Any, lifetime: float | None = None) -> None: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def set_multi(
        self,
        mydict: builtins.dict[Any, Any],
        lifetime: float | None = 0,
        pause: bool = False,
    ) -> list[Any]: ...
    def set_local(self, key: Any, value: Any, lifetime: float | None = None) -> None: ...
    def delete(self, key: Any) -> bool: ...
    def __delitem__(self, key: Any) -> None: ...
    def delete_multi(self, keys: Iterable[Any]) -> bool: ...
    def clear(self, block: bool = False) -> None: ...
    def replicate_clear(self, clear_count: Any) -> bool: ...
    def replicate_clear_if_necessary(self) -> bool: ...
    def was_cleared(self) -> bool: ...

class MemcachedCache(PdsCache):
    port: int | str
    mc: Any
    lifetime: int | None
    lifetime_func: Callable[[Any], float] | None
    local_value_by_key: dict[Any, Any]
    local_lifetime_by_key: dict[Any, int | float]
    local_keys_by_lifetime: dict[int | float, list[Any]]
    pauses: int
    permanent_values: dict[Any, Any]
    toobig_dict: dict[Any, Any]
    logger: _PdsLogger | None
    pid: int
    clear_count: int
    def __init__(
        self,
        port: int | str = 11211,
        lifetime: float | Callable[[Any], float] = 86400,
        logger: _PdsLogger | None = None,
    ) -> None: ...
    def wait_for_unblock(self, funcname: str = '') -> bool: ...
    def wait_and_block(self, funcname: str = '') -> bool: ...
    def unblock(self, flush: bool = True) -> None: ...
    def is_blocked(self) -> int: ...
    def pause(self) -> None: ...
    @property
    def is_paused(self) -> bool: ...
    def resume(self) -> None: ...
    def __contains__(self, key: Any) -> bool: ...
    def __len__(self) -> int: ...
    def len_mc(self) -> int: ...
    def flush(self) -> None: ...
    def get(self, key: Any) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def get_multi(self, keys: Iterable[Any]) -> builtins.dict[Any, Any]: ...
    def get_local(self, key: Any) -> Any: ...
    def get_now(self, key: Any) -> Any: ...
    def set(self, key: Any, value: Any, lifetime: float | None = None) -> bool | None: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def set_multi(self, mydict: dict[Any, Any], lifetime: float | None = None) -> list[Any]: ...
    def set_local(self, key: Any, value: Any, lifetime: float | None = None) -> None: ...
    def delete(self, key: Any) -> bool: ...
    def __delitem__(self, key: Any) -> None: ...
    def delete_multi(self, keys: list[Any]) -> bool: ...
    def clear(self, block: bool = False) -> None: ...
    def replicate_clear(self, clear_count: int | None) -> bool: ...
    def replicate_clear_if_necessary(self) -> bool: ...
    def was_cleared(self) -> bool: ...
