"""Type stubs for ``pdsfile.pdsfile`` (see the module docstring there).

The implementation is unannotated (modernization ground rule 5); these stubs
declare the public surface frozen in ``tests/api/api_manifest.json``. Types are
derived from the implementation and its docstrings; where the truth is broader
than a single concrete type, the broader type is declared, and ``Any`` marks a
value whose type flows through an untyped dependency (rms-translator,
rms-pdslogger, rms-pdsparser, rms-pdstable ship no py.typed marker) or through
pickled/eval'd shelf content that nothing in this package constrains.

The ``PdsFile`` class assembles its behavior from nine private mixin modules;
the manifest records the members on the class itself, and this stub declares
them the same way, grouped by the module that defines each. ``CACHE`` is a
union because ``preload(port=...)`` rebinds it to a ``MemcachedCache``.
"""

# The manifest freezes the imported-module names below as public attributes of
# this module, so the stubs re-export them.
import bisect as bisect
import datetime as datetime
import fnmatch as fnmatch
import functools as functools
import glob as glob
import math as math
import numbers as numbers
import os as os
import pickle as pickle
import re as re
import time as time
from collections import defaultdict as defaultdict
from collections.abc import Collection, Iterable, Sequence
from typing import Any, Self

import pdslogger as pdslogger  # type: ignore[import-untyped]
import pdsparser as pdsparser  # type: ignore[import-untyped]
import pdstable as pdstable  # type: ignore[import-untyped]
import PIL as PIL
import translator as translator  # type: ignore[import-untyped]

from pdsfile import pdscache as pdscache
from pdsfile import pdsviewable as pdsviewable
from pdsfile.pdscache import DictionaryCache, MemcachedCache
from pdsfile.pdsviewable import PdsViewSet

# rms-pdslogger and rms-translator ship no py.typed marker, so their classes
# cannot be named here.
_PdsLogger = Any
_Translator = Any

FILE_BYTE_UNITS: list[str]
HAS_PYLIBMC: bool
PATH_EXISTS_CACHE_SIZE: int

def abspath_for_logical_path(path: str, cls: type[PdsFile]) -> str: ...
def cache_lifetime_for_class(arg: Any, cls: type[PdsFile] | None = None) -> int: ...
def construct_category_list(voltypes: Collection[str]) -> list[str]: ...
def formatted_file_size(size: float) -> str: ...
def logical_path_from_abspath(abspath: str, cls: type[PdsFile]) -> str: ...
def pause_caching(cls: type[PdsFile]) -> None: ...
def repair_case(abspath: str, cls: type[PdsFile]) -> str: ...
def resume_caching(cls: type[PdsFile]) -> None: ...
def selected_path_from_path(path: str, cls: type[PdsFile],
                            abspaths: bool = True) -> str: ...

class PdsFile:
    # Class attributes and members defined in pdsfile.py itself
    ASSOCIATIONS: dict[str, _Translator] | None
    BUNDLE_DIR_NAME: str
    CACHE: DictionaryCache | MemcachedCache
    CATEGORIES: set[str]
    CATEGORY_LIST: list[str]
    CATEGORY_REGEX: re.Pattern[str]
    CATEGORY_REGEX_I: re.Pattern[str]
    DATAFILE_EXTS: set[str]
    DATA_SET_ID: _Translator | None
    DEFAULT_CACHING: str
    DEFAULT_HIGH_LEVEL_ICONS: dict[tuple[str, bool], str]
    DESCRIPTION_AND_ICON: _Translator | None
    DICTIONARY_CACHE_LIMIT: int
    EXTRA_README_BASENAMES: tuple[str, ...]
    FILENAME_KEYLEN: int
    FILESPEC_TO_BUNDLESET: _Translator | None
    FS_IS_CASE_INSENSITIVE: bool
    INFO_FILE_BASENAMES: _Translator | None
    LATEST_VERSION_RANKS: list[int]
    LID_AFTER_DSID: _Translator | None
    LOCAL_HOLDINGS_DIRS: list[str] | None
    LOCAL_PRELOADED: list[str]
    LOGFILE_TIME_FMT: str
    LOGGER: _PdsLogger
    LOG_ROOT_: str | None
    MEMCACHE_PORT: int
    MIME_TYPES_VS_EXT: dict[str, str]
    NEIGHBORS: _Translator | None
    OPUS_FORMAT: _Translator | None
    OPUS_ID: _Translator | None
    OPUS_ID_TO_PRIMARY_LOGICAL_PATH: _Translator | None
    OPUS_ID_TO_SUBCLASS: _Translator | None
    OPUS_PRODUCTS: _Translator | None
    OPUS_TYPE: _Translator | None
    PDS_HOLDINGS: str
    PLAIN_TEXT_EXTS: set[str]
    PRELOAD_TRIES: int
    PRODUCT_LBL_BASENAME_WO_EXT: _Translator | None
    SHELF_ACCESS: dict[str, int]
    SHELF_ACCESS_COUNT: int
    SHELF_CACHE: dict[str, Any]
    SHELF_CACHE_SIZE: int
    SHELF_CACHE_SLOP: int
    SHELF_NULL_KEY_VALUES: dict[str, Any]
    SHELF_PATH_INFO: dict[str, tuple[str, str]]
    SHELVES_ONLY: bool
    SHELVES_REQUIRED: bool
    SIBLINGS: _Translator | None
    SORT_KEY: _Translator | None
    SORT_ORDER: dict[str, bool | int]
    SPLIT_RULES: _Translator | None
    SUBCLASSES: dict[str, type[PdsFile]]
    VERSIONS: _Translator | None
    VIEWABLES: dict[str, _Translator] | None
    VIEWABLE_ANCHOR_REGEX: re.Pattern[str]
    VIEWABLE_EXTS: set[str]
    VIEWABLE_VOLTYPES: list[str]
    VIEW_OPTIONS: _Translator | None
    VOLSET_TRANSLATOR: _Translator
    VOLTYPES: list[str]
    def bundle_abspath(self, category: str | None = None) -> str: ...
    def bundle_pdsfile(self, category: str | None = None,
                       rank: int | None = None) -> PdsFile | None: ...
    def bundleset_abspath(self, category: str | None = None) -> str | None: ...
    def bundleset_pdsfile(self, category: str | None = None,
                          rank: int | None = None) -> PdsFile | None: ...
    def child(self, basename: str, fix_case: bool = True, must_exist: bool = False,
              caching: str = 'default', lifetime: float | None = None,
              allow_index_row: bool = True) -> PdsFile: ...
    def copy(self) -> Self: ...
    @classmethod
    def from_abspath(cls, abspath: str, fix_case: bool = False,
                     must_exist: bool = False, caching: str = 'default',
                     lifetime: float | None = None) -> PdsFile: ...
    @classmethod
    def from_lid(cls, lid_str: str) -> PdsFile: ...
    @classmethod
    def from_logical_path(cls, path: str, fix_case: bool = False,
                          must_exist: bool = False, caching: str = 'default',
                          lifetime: float | None = None) -> PdsFile | None: ...
    @classmethod
    def from_path(cls, path: Any, must_exist: bool = False, caching: str = 'default',
                  lifetime: float | None = None) -> PdsFile: ...
    def from_relative_path(self, path: str, fix_case: bool = False,
                           must_exist: bool = False, caching: str = 'default',
                           lifetime: float | None = None) -> PdsFile: ...
    @property
    def is_bundle(self) -> bool: ...
    @property
    def is_bundle_dir(self) -> bool: ...
    @property
    def is_bundle_file(self) -> bool: ...
    @property
    def is_bundleset(self) -> bool: ...
    @property
    def is_bundleset_dir(self) -> bool: ...
    @property
    def is_bundleset_file(self) -> bool: ...
    @property
    def is_category_dir(self) -> bool: ...
    @classmethod
    def is_logical_path(cls, path: str) -> bool: ...
    def new_index_row_pdsfile(self, filename_key: str,
                              row_dicts: list[dict[Any, Any]]) -> Self: ...
    @classmethod
    def new_merged_dir(cls, basename: str) -> Self: ...
    def new_pdsfile(self, key: str | None = None, copypath: bool = False) -> PdsFile: ...
    def parent(self, must_exist: bool = False, caching: str = 'default',
               lifetime: float | None = None) -> PdsFile | None: ...
    @classmethod
    def require_shelves(cls, status: bool = True) -> None: ...
    @classmethod
    def set_easylogger(cls) -> None: ...
    @classmethod
    def set_logger(cls, logger: _PdsLogger | None = None) -> None: ...
    def sort_dirs_first(self, dirs_first: bool) -> None: ...
    def sort_dirs_last(self, dirs_last: bool) -> None: ...
    def sort_info_first(self, info_first: bool | int) -> None: ...
    def sort_labels_after(self, labels_after: bool) -> None: ...
    @classmethod
    def use_shelves_only(cls, status: bool = True) -> None: ...

    # Members defined in the private mixin module _properties.py
    @property
    def absolute_or_logical_path(self) -> str: ...
    @property
    def all_version_abspaths(self) -> dict[int, str | None]: ...
    def all_versions(self) -> dict[int, PdsFile]: ...
    @property
    def all_viewsets(self) -> dict[str, PdsViewSet]: ...
    @property
    def alt(self) -> str: ...
    @property
    def anchor(self) -> Any: ...
    @property
    def bundle_publication_date(self) -> Any: ...
    @property
    def bundle_version_id(self) -> Any: ...
    @property
    def checksum(self) -> Any: ...
    @property
    def childnames(self) -> list[Any]: ...
    @property
    def childnames_lc(self) -> list[Any]: ...
    @property
    def continuous_view_allowed(self) -> Any: ...
    @property
    def data_abspaths(self) -> list[str]: ...
    @property
    def data_set_id(self) -> Any: ...
    @property
    def date(self) -> Any: ...
    @property
    def description(self) -> Any: ...
    @property
    def exact_archive_url(self) -> str: ...
    @property
    def exact_checksum_url(self) -> str: ...
    @property
    def exists(self) -> bool: ...
    @property
    def extension(self) -> Any: ...
    @property
    def filename_keylen(self) -> Any: ...
    @property
    def filespec(self) -> str: ...
    @property
    def formatted_size(self) -> str: ...
    @property
    def global_anchor(self) -> str: ...
    @property
    def grid_view_allowed(self) -> Any: ...
    @property
    def has_neighbor_rule(self) -> bool: ...
    @property
    def height(self) -> Any: ...
    @property
    def html_path(self) -> str: ...
    @property
    def icon_type(self) -> Any: ...
    @property
    def iconset_closed(self) -> PdsViewSet: ...
    @property
    def iconset_open(self) -> PdsViewSet: ...
    @property
    def index_pdslabel(self) -> Any: ...
    @property
    def indexshelf_abspath(self) -> str: ...
    @property
    def info_basename(self) -> Any: ...
    @property
    def infoshelf_path_and_key(self) -> tuple[str, str]: ...
    @property
    def internal_link_info(self) -> str | list[tuple[Any, Any, str]] | tuple[()]: ...
    @property
    def is_documents(self) -> bool: ...
    @property
    def is_index(self) -> bool: ...
    @property
    def is_label(self) -> bool: ...
    @property
    def is_viewable(self) -> bool: ...
    @property
    def isdir(self) -> bool: ...
    @property
    def islabel(self) -> bool: ...
    @property
    def label_abspath(self) -> str: ...
    @property
    def label_basename(self) -> Any: ...
    @property
    def lid(self) -> Any: ...
    @property
    def lidvid(self) -> Any: ...
    @property
    def linked_abspaths(self) -> list[str]: ...
    @property
    def local_viewset(self) -> PdsViewSet | bool | None: ...
    @property
    def mime_type(self) -> str: ...
    @property
    def modtime(self) -> Any: ...
    @property
    def multipage_view_allowed(self) -> Any: ...
    @property
    def opus_format(self) -> Any: ...
    @property
    def opus_id(self) -> Any: ...
    @property
    def opus_type(self) -> Any: ...
    @property
    def parent_logical_path(self) -> str: ...
    @property
    def size_bytes(self) -> Any: ...
    @property
    def split(self) -> Any: ...
    @property
    def url(self) -> str: ...
    @staticmethod
    def version_info(suffix: str | None) -> tuple[int, str, str]: ...
    @property
    def version_ranks(self) -> Any: ...
    @property
    def viewset(self) -> PdsViewSet | bool: ...
    def viewset_lookup(self, name: str = 'default') -> PdsViewSet | None: ...
    @property
    def volume_data_set_ids(self) -> Any: ...
    @property
    def width(self) -> Any: ...

    # Members defined in _index_rows.py, _shelves.py and _sorting.py
    # --- pdsfile._index_rows ---
    def child_of_index(self, selection: str, flag: str = '=') -> PdsFile: ...
    def data_abspath_associated_with_index_row(self) -> str: ...
    def data_pdsfile_for_index_row(self) -> PdsFile | None: ...
    def find_selected_row_key(self, selection: str, flag: str = '=', exact_match: bool = False) -> Any: ...
    def get_indexshelf(self) -> dict[Any, Any]: ...
    # --- pdsfile._shelves ---
    @classmethod
    def close_all_shelves(cls) -> None: ...
    @property
    def info_shelf_expected(self) -> bool: ...
    def shelf_exists_if_expected(self) -> bool | None: ...
    def shelf_lookup(self, shelf_type: str = 'info', bundlename: str = '') -> Any: ...
    def shelf_path_and_key(self, shelf_id: str = 'info', bundlename: str = '') -> tuple[str, str]: ...
    @classmethod
    def shelf_path_and_key_for_abspath(cls, abspath: str, shelf_type: str = 'info') -> tuple[str, str]: ...
    def shelf_path_and_lskip(self, shelf_type: str = 'info', bundlename: str = '') -> tuple[str, int]: ...
    # --- pdsfile._sorting ---
    def abspaths_for_basenames(self, basenames: Iterable[str], must_exist: bool = False) -> list[str | None]: ...
    @classmethod
    def abspaths_for_logicals(cls, logical_paths: Iterable[str], must_exist: bool = False) -> list[str]: ...
    @staticmethod
    def abspaths_for_pdsfiles(pdsfiles: Iterable[PdsFile], must_exist: bool = False) -> list[str]: ...
    def basename_is_label(self, basename: str) -> bool: ...
    def basename_is_viewable(self, basename: str | None = None) -> bool: ...
    @classmethod
    def basenames_for_abspaths(cls, abspaths: Iterable[str], must_exist: bool = False) -> list[str]: ...
    @classmethod
    def basenames_for_logicals(cls, logical_paths: Iterable[str], must_exist: bool = False) -> list[str]: ...
    @staticmethod
    def basenames_for_pdsfiles(pdsfiles: Iterable[PdsFile], must_exist: bool = False) -> list[str]: ...
    def childnames_by_anchor(self, anchor: str) -> list[Any]: ...
    @classmethod
    def logicals_for_abspaths(cls, abspaths: Iterable[str], must_exist: bool = False) -> list[str]: ...
    def logicals_for_basenames(self, basenames: Iterable[str], must_exist: bool = False) -> list[str]: ...
    @staticmethod
    def logicals_for_pdsfiles(pdsfiles: Iterable[PdsFile], must_exist: bool = False) -> list[str]: ...
    @classmethod
    def pdsfiles_for_abspaths(cls, abspaths: Iterable[str], must_exist: bool = False) -> list[PdsFile]: ...
    def pdsfiles_for_basenames(self, basenames: Iterable[str], must_exist: bool = False) -> list[PdsFile]: ...
    @classmethod
    def pdsfiles_for_logicals(cls, logical_paths: Iterable[str], must_exist: bool = False) -> list[PdsFile | None]: ...
    def sort_basenames(self, basenames: Sequence[str], labels_after: bool | None = None, dirs_first: bool | None = None, dirs_last: bool | None = None, info_first: int | None = None) -> list[str]: ...
    def sort_childnames(self, labels_after: bool | None = None, dirs_first: bool | None = None) -> list[Any]: ...
    @classmethod
    def sort_logical_paths(cls, logical_paths: Collection[str]) -> list[str]: ...
    def sort_siblings(self, siblings: Iterable[PdsFile], labels_after: bool | None = None, dirs_first: bool | None = None, dirs_last: bool | None = None, info_first: int | None = None) -> list[PdsFile]: ...
    def sort_sibnames(self, basenames: list[str], labels_after: bool | None = None, dirs_first: bool | None = None, dirs_last: bool | None = None, info_first: int | None = None) -> list[str]: ...
    def split_basename(self, basename: str = '') -> Any: ...
    def viewable_childnames(self) -> list[Any]: ...
    def viewable_childnames_by_anchor(self, anchor: str) -> list[Any]: ...

    # Members defined in _associations.py, _derived_paths.py,
    # _local_fs.py, _opus.py and _preload.py
    def associated_abspaths(self, category: str, must_exist: bool = True) -> list[str]: ...
    def associated_logical_paths(self, category: str, must_exist: bool = True) -> list[str]: ...
    def associated_parallel(self, category: str | None = None,
                            rank: int | str | None = None) -> PdsFile | None: ...
    def associated_pdsfiles(self, category: str, must_exist: bool = True) -> list[PdsFile]: ...
    def archive_logpath(self, task: str) -> str: ...
    def archive_path_and_lskip(self) -> tuple[str, int]: ...
    def archive_path_if_exact(self) -> str: ...
    def checksum_path_and_lskip(self) -> tuple[str, int]: ...
    def checksum_path_if_exact(self) -> str: ...
    def dirpath_and_prefix_for_archive(self) -> tuple[str, str]: ...
    def dirpath_and_prefix_for_checksum(self) -> tuple[str, str]: ...
    def log_path_for_bundle(self, suffix: str = '', task: str = '', dir: str = '',
                            place: str = 'default') -> str: ...
    def log_path_for_bundleset(self, suffix: str = '', task: str = '', dir: str = '',
                               place: str = 'default') -> str: ...
    def log_path_for_index(self, task: str = '', dir: str = 'index',
                           place: str = 'default') -> str: ...
    @classmethod
    def set_log_root(cls, root: str | None = None) -> None: ...
    @classmethod
    def glob_glob(cls, abspath: str, force_case_sensitive: bool = False) -> list[str]: ...
    @classmethod
    def os_listdir(cls, abspath: str) -> list[str]: ...
    @classmethod
    def os_path_exists(cls, abspath: str, force_case_sensitive: bool = False) -> bool: ...
    @classmethod
    def os_path_isdir(cls, abspath: str) -> bool: ...
    @classmethod
    def from_filespec(cls, filespec: str, fix_case: bool = False) -> PdsFile: ...
    @classmethod
    def from_opus_id(cls, opus_id: str) -> Any: ...
    def opus_products(self) -> dict[Any, list[list[PdsFile]]]: ...
    @classmethod
    def cache_category_merged_dirs(cls) -> None: ...
    @classmethod
    def cache_lifetime(cls, arg: Any) -> int: ...
    @classmethod
    def get_permanent_values(cls, holdings_list: str | list[str] | tuple[str, ...],
                             port: int) -> None: ...
    @classmethod
    def load_volume_info(cls, holdings: str) -> None: ...
    @classmethod
    def preload(cls, holdings_list: str | list[str] | tuple[str, ...], port: int = 0,
                clear: bool = False, force_reload: bool = False,
                icon_url: str | None = None, icon_color: str = 'blue') -> None: ...

    # Public instance attributes (assigned in __init__ and the
    # constructors; see also the per-member docstrings in the source)

    basename: str
    abspath: str | None
    logical_path: str
    disk_: str | None
    root_: str | None
    html_root_: str | None
    category_: str
    checksums_: str
    archives_: str
    bundletype_: str
    bundleset_: str
    bundleset: str
    suffix: str
    version_message: str
    version_rank: int
    version_id: str
    bundlename_: str
    bundlename: str
    interior: str
    is_index_row: bool
    row_dicts: list[dict[Any, Any]]
    column_names: list[Any]
    permanent: bool
    is_merged: bool
    parent_basename: str
